import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "../components/ui/provider";
import { Toaster } from "@/components/ui/toaster";
import { ConvexClientProvider } from "./providers/ConvexClientProvider";
import ClientThemeProvider from "@/components/ClientThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientThemeProvider>
          <ConvexClientProvider>
            <Provider>
                {children}
                <Toaster></Toaster>
            </Provider>
          </ConvexClientProvider>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
